import type { TOption } from "@/types";

export const cities: Record<
  string,
  TOption[]
> = {
  Afghanistan: [
    { label: "Kabul", value: "Kabul" },
    { label: "Kandahar", value: "Kandahar" },
    { label: "Herat", value: "Herat" },
    { label: "Mazar-i-Sharif", value: "Mazar-i-Sharif" },
    { label: "Jalalabad", value: "Jalalabad" },
    { label: "Kunduz", value: "Kunduz" },
    { label: "Balkh", value: "Balkh" },
    { label: "Ghazni", value: "Ghazni" },
  ],

  Albania: [
    { label: "Tirana", value: "Tirana" },
    { label: "Durrës", value: "Durres" },
    { label: "Vlorë", value: "Vlore" },
    { label: "Elbasan", value: "Elbasan" },
    { label: "Shkodër", value: "Shkoder" },
    { label: "Fier", value: "Fier" },
    { label: "Korçë", value: "Korce" },
    { label: "Berat", value: "Berat" },
  ],

  Algeria: [
    { label: "Algiers", value: "Algiers" },
    { label: "Oran", value: "Oran" },
    { label: "Constantine", value: "Constantine" },
    { label: "Annaba", value: "Annaba" },
    { label: "Blida", value: "Blida" },
    { label: "Sétif", value: "Setif" },
    { label: "Djelfa", value: "Djelfa" },
    { label: "Sidi Bel Abbès", value: "Sidi Bel Abbes" },
  ],

  Argentina: [
    { label: "Buenos Aires", value: "Buenos Aires" },
    { label: "Córdoba", value: "Cordoba" },
    { label: "Rosario", value: "Rosario" },
    { label: "Mendoza", value: "Mendoza" },
    { label: "La Plata", value: "La Plata" },
    { label: "San Miguel de Tucumán", value: "San Miguel de Tucuman" },
    { label: "Mar del Plata", value: "Mar del Plata" },
    { label: "Salta", value: "Salta" },
    { label: "Santa Fe", value: "Santa Fe" },
    { label: "San Juan", value: "San Juan" },
  ],

  Armenia: [
    { label: "Yerevan", value: "Yerevan" },
    { label: "Gyumri", value: "Gyumri" },
    { label: "Vanadzor", value: "Vanadzor" },
    { label: "Vagharshapat", value: "Vagharshapat" },
    { label: "Hrazdan", value: "Hrazdan" },
    { label: "Abovyan", value: "Abovyan" },
    { label: "Kapan", value: "Kapan" },
    { label: "Ararat", value: "Ararat" },
    { label: "Armavir", value: "Armavir" },
    { label: "Gavar", value: "Gavar" },
  ],

  Australia: [
    { label: "Sydney", value: "Sydney" },
    { label: "Melbourne", value: "Melbourne" },
    { label: "Brisbane", value: "Brisbane" },
    { label: "Perth", value: "Perth" },
    { label: "Adelaide", value: "Adelaide" },
    { label: "Gold Coast", value: "Gold Coast" },
    { label: "Canberra", value: "Canberra" },
    { label: "Hobart", value: "Hobart" },
    { label: "Darwin", value: "Darwin" },
  ],

  Austria: [
    { label: "Vienna", value: "Vienna" },
    { label: "Salzburg", value: "Salzburg" },
    { label: "Graz", value: "Graz" },
    { label: "Linz", value: "Linz" },
    { label: "Innsbruck", value: "Innsbruck" },
    { label: "Klagenfurt", value: "Klagenfurt" },
    { label: "Villach", value: "Villach" },
    { label: "Wels", value: "Wels" },
    { label: "Sankt Pölten", value: "Sankt Polten" },
    { label: "Dornbirn", value: "Dornbirn" },
  ],

  Azerbaijan: [
    { label: "Baku", value: "Baku" },
    { label: "Ganja", value: "Ganja" },
    { label: "Sumqayit", value: "Sumqayit" },
    { label: "Mingachevir", value: "Mingachevir" },
    { label: "Lankaran", value: "Lankaran" },
    { label: "Shirvan", value: "Shirvan" },
    { label: "Nakhchivan", value: "Nakhchivan" },
    { label: "Shaki", value: "Shaki" },
  ],

  Bangladesh: [
    { label: "Dhaka", value: "Dhaka" },
    { label: "Chittagong", value: "Chittagong" },
    { label: "Khulna", value: "Khulna" },
    { label: "Rajshahi", value: "Rajshahi" },
    { label: "Sylhet", value: "Sylhet" },
    { label: "Barisal", value: "Barisal" },
    { label: "Rangpur", value: "Rangpur" },
    { label: "Comilla", value: "Comilla" },
  ],

  Belarus: [
    { label: "Minsk", value: "Minsk" },
    { label: "Gomel", value: "Gomel" },
    { label: "Mogilev", value: "Mogilev" },
    { label: "Vitebsk", value: "Vitebsk" },
    { label: "Grodno", value: "Grodno" },
    { label: "Brest", value: "Brest" },
    { label: "Bobruisk", value: "Bobruisk" },
    { label: "Baranovichi", value: "Baranovichi" },
  ],

  Belgium: [
    { label: "Brussels", value: "Brussels" },
    { label: "Antwerp", value: "Antwerp" },
    { label: "Ghent", value: "Ghent" },
    { label: "Charleroi", value: "Charleroi" },
    { label: "Liège", value: "Liege" },
    { label: "Bruges", value: "Bruges" },
    { label: "Namur", value: "Namur" },
    { label: "Leuven", value: "Leuven" },
    { label: "Mons", value: "Mons" },
    { label: "Aalst", value: "Aalst" },
  ],

  Brazil: [
    { label: "São Paulo", value: "Sao Paulo" },
    { label: "Rio de Janeiro", value: "Rio de Janeiro" },
    { label: "Brasília", value: "Brasilia" },
    { label: "Salvador", value: "Salvador" },
    { label: "Fortaleza", value: "Fortaleza" },
    { label: "Belo Horizonte", value: "Belo Horizonte" },
    { label: "Manaus", value: "Manaus" },
    { label: "Curitiba", value: "Curitiba" },
    { label: "Recife", value: "Recife" },
    { label: "Porto Alegre", value: "Porto Alegre" },
  ],

  Bulgaria: [
    { label: "Sofia", value: "Sofia" },
    { label: "Plovdiv", value: "Plovdiv" },
    { label: "Varna", value: "Varna" },
    { label: "Burgas", value: "Burgas" },
    { label: "Ruse", value: "Ruse" },
    { label: "Stara Zagora", value: "Stara Zagora" },
    { label: "Pleven", value: "Pleven" },
    { label: "Sliven", value: "Sliven" },
  ],

  Canada: [
    { label: "Toronto", value: "Toronto" },
    { label: "Vancouver", value: "Vancouver" },
    { label: "Montreal", value: "Montreal" },
    { label: "Calgary", value: "Calgary" },
    { label: "Ottawa", value: "Ottawa" },
    { label: "Edmonton", value: "Edmonton" },
    { label: "Quebec City", value: "Quebec City" },
    { label: "Winnipeg", value: "Winnipeg" },
    { label: "Hamilton", value: "Hamilton" },
    { label: "Halifax", value: "Halifax" },
  ],

  Chile: [
    { label: "Santiago", value: "Santiago" },
    { label: "Valparaíso", value: "Valparaiso" },
    { label: "Concepción", value: "Concepcion" },
    { label: "La Serena", value: "La Serena" },
    { label: "Antofagasta", value: "Antofagasta" },
    { label: "Temuco", value: "Temuco" },
    { label: "Rancagua", value: "Rancagua" },
    { label: "Arica", value: "Arica" },
    { label: "Puerto Montt", value: "Puerto Montt" },
    { label: "Iquique", value: "Iquique" },
  ],

  China: [
    { label: "Beijing", value: "Beijing" },
    { label: "Shanghai", value: "Shanghai" },
    { label: "Guangzhou", value: "Guangzhou" },
    { label: "Shenzhen", value: "Shenzhen" },
    { label: "Chengdu", value: "Chengdu" },
    { label: "Chongqing", value: "Chongqing" },
    { label: "Xi'an", value: "Xian" },
    { label: "Hangzhou", value: "Hangzhou" },
    { label: "Nanjing", value: "Nanjing" },
    { label: "Wuhan", value: "Wuhan" },
  ],

  Colombia: [
    { label: "Bogotá", value: "Bogota" },
    { label: "Medellín", value: "Medellin" },
    { label: "Cali", value: "Cali" },
    { label: "Barranquilla", value: "Barranquilla" },
    { label: "Cartagena", value: "Cartagena" },
    { label: "Cúcuta", value: "Cucuta" },
    { label: "Bucaramanga", value: "Bucaramanga" },
    { label: "Pereira", value: "Pereira" },
    { label: "Santa Marta", value: "Santa Marta" },
    { label: "Ibagué", value: "Ibague" },
  ],

  Croatia: [
    { label: "Zagreb", value: "Zagreb" },
    { label: "Split", value: "Split" },
    { label: "Rijeka", value: "Rijeka" },
    { label: "Osijek", value: "Osijek" },
    { label: "Zadar", value: "Zadar" },
    { label: "Dubrovnik", value: "Dubrovnik" },
    { label: "Pula", value: "Pula" },
    { label: "Šibenik", value: "Sibenik" },
  ],

  Cyprus: [
    { label: "Nicosia", value: "Nicosia" },
    { label: "Limassol", value: "Limassol" },
    { label: "Larnaca", value: "Larnaca" },
    { label: "Famagusta", value: "Famagusta" },
    { label: "Paphos", value: "Paphos" },
    { label: "Kyrenia", value: "Kyrenia" },
    { label: "Protaras", value: "Protaras" },
    { label: "Paralimni", value: "Paralimni" },
  ],

  "Czech Republic": [
    { label: "Prague", value: "Prague" },
    { label: "Brno", value: "Brno" },
    { label: "Ostrava", value: "Ostrava" },
    { label: "Plzeň", value: "Plzen" },
    { label: "Liberec", value: "Liberec" },
    { label: "Olomouc", value: "Olomouc" },
    { label: "České Budějovice", value: "Ceske Budejovice" },
    { label: "Hradec Králové", value: "Hradec Kralove" },
    { label: "Ústí nad Labem", value: "Usti nad Labem" },
    { label: "Pardubice", value: "Pardubice" },
  ],

  Denmark: [
    { label: "Copenhagen", value: "Copenhagen" },
    { label: "Aarhus", value: "Aarhus" },
    { label: "Odense", value: "Odense" },
    { label: "Aalborg", value: "Aalborg" },
    { label: "Esbjerg", value: "Esbjerg" },
    { label: "Randers", value: "Randers" },
    { label: "Kolding", value: "Kolding" },
    { label: "Helsingør", value: "Helsingor" },
  ],

  Egypt: [
    { label: "Cairo", value: "Cairo" },
    { label: "Alexandria", value: "Alexandria" },
    { label: "Giza", value: "Giza" },
    { label: "Shubra El Kheima", value: "Shubra El Kheima" },
    { label: "Port Said", value: "Port Said" },
    { label: "Suez", value: "Suez" },
    { label: "Luxor", value: "Luxor" },
    { label: "Aswan", value: "Aswan" },
    { label: "Mansoura", value: "Mansoura" },
    { label: "Tanta", value: "Tanta" },
  ],

  Estonia: [
    { label: "Tallinn", value: "Tallinn" },
    { label: "Tartu", value: "Tartu" },
    { label: "Narva", value: "Narva" },
    { label: "Pärnu", value: "Parnu" },
    { label: "Kohtla-Järve", value: "Kohtla-Jarve" },
    { label: "Viljandi", value: "Viljandi" },
    { label: "Rakvere", value: "Rakvere" },
    { label: "Kuressaare", value: "Kuressaare" },
  ],

  Finland: [
    { label: "Helsinki", value: "Helsinki" },
    { label: "Espoo", value: "Espoo" },
    { label: "Tampere", value: "Tampere" },
    { label: "Vantaa", value: "Vantaa" },
    { label: "Oulu", value: "Oulu" },
    { label: "Turku", value: "Turku" },
    { label: "Jyväskylä", value: "Jyvaskyla" },
    { label: "Lahti", value: "Lahti" },
  ],

  France: [
    { label: "Paris", value: "Paris" },
    { label: "Lyon", value: "Lyon" },
    { label: "Marseille", value: "Marseille" },
    { label: "Nice", value: "Nice" },
    { label: "Toulouse", value: "Toulouse" },
    { label: "Bordeaux", value: "Bordeaux" },
    { label: "Lille", value: "Lille" },
    { label: "Strasbourg", value: "Strasbourg" },
    { label: "Nantes", value: "Nantes" },
    { label: "Montpellier", value: "Montpellier" },
  ],

  Georgia: [
    { label: "Tbilisi", value: "Tbilisi" },
    { label: "Batumi", value: "Batumi" },
    { label: "Kutaisi", value: "Kutaisi" },
    { label: "Rustavi", value: "Rustavi" },
    { label: "Gori", value: "Gori" },
    { label: "Zugdidi", value: "Zugdidi" },
    { label: "Poti", value: "Poti" },
    { label: "Telavi", value: "Telavi" },
  ],

  Germany: [
    { label: "Berlin", value: "Berlin" },
    { label: "Munich", value: "Munich" },
    { label: "Hamburg", value: "Hamburg" },
    { label: "Frankfurt", value: "Frankfurt" },
    { label: "Cologne", value: "Cologne" },
    { label: "Stuttgart", value: "Stuttgart" },
    { label: "Düsseldorf", value: "Dusseldorf" },
    { label: "Dortmund", value: "Dortmund" },
    { label: "Essen", value: "Essen" },
    { label: "Leipzig", value: "Leipzig" },
    { label: "Bremen", value: "Bremen" },
    { label: "Dresden", value: "Dresden" },
  ],

  Greece: [
    { label: "Athens", value: "Athens" },
    { label: "Thessaloniki", value: "Thessaloniki" },
    { label: "Patras", value: "Patras" },
    { label: "Heraklion", value: "Heraklion" },
    { label: "Larissa", value: "Larissa" },
    { label: "Volos", value: "Volos" },
    { label: "Rhodes", value: "Rhodes" },
    { label: "Ioannina", value: "Ioannina" },
    { label: "Chania", value: "Chania" },
    { label: "Chalcis", value: "Chalcis" },
  ],

  Hungary: [
    { label: "Budapest", value: "Budapest" },
    { label: "Debrecen", value: "Debrecen" },
    { label: "Szeged", value: "Szeged" },
    { label: "Miskolc", value: "Miskolc" },
    { label: "Pécs", value: "Pecs" },
    { label: "Győr", value: "Gyor" },
    { label: "Nyíregyháza", value: "Nyiregyhaza" },
    { label: "Kecskemét", value: "Kecskemet" },
    { label: "Székesfehérvár", value: "Szekesfehervar" },
    { label: "Szombathely", value: "Szombathely" },
  ],

  India: [
    { label: "Mumbai", value: "Mumbai" },
    { label: "Delhi", value: "Delhi" },
    { label: "Bangalore", value: "Bangalore" },
    { label: "Hyderabad", value: "Hyderabad" },
    { label: "Chennai", value: "Chennai" },
    { label: "Kolkata", value: "Kolkata" },
    { label: "Pune", value: "Pune" },
    { label: "Ahmedabad", value: "Ahmedabad" },
    { label: "Jaipur", value: "Jaipur" },
    { label: "Lucknow", value: "Lucknow" },
  ],

  Indonesia: [
    { label: "Jakarta", value: "Jakarta" },
    { label: "Surabaya", value: "Surabaya" },
    { label: "Bandung", value: "Bandung" },
    { label: "Medan", value: "Medan" },
    { label: "Semarang", value: "Semarang" },
    { label: "Makassar", value: "Makassar" },
    { label: "Palembang", value: "Palembang" },
    { label: "Denpasar", value: "Denpasar" },
    { label: "Yogyakarta", value: "Yogyakarta" },
    { label: "Malang", value: "Malang" },
  ],

  Iran: [
    { label: "Tehran", value: "Tehran" },
    { label: "Mashhad", value: "Mashhad" },
    { label: "Isfahan", value: "Isfahan" },
    { label: "Karaj", value: "Karaj" },
    { label: "Shiraz", value: "Shiraz" },
    { label: "Tabriz", value: "Tabriz" },
    { label: "Qom", value: "Qom" },
    { label: "Ahvaz", value: "Ahvaz" },
    { label: "Kermanshah", value: "Kermanshah" },
    { label: "Rasht", value: "Rasht" },
  ],

  Iraq: [
    { label: "Baghdad", value: "Baghdad" },
    { label: "Basra", value: "Basra" },
    { label: "Mosul", value: "Mosul" },
    { label: "Erbil", value: "Erbil" },
    { label: "Kirkuk", value: "Kirkuk" },
    { label: "Najaf", value: "Najaf" },
    { label: "Karbala", value: "Karbala" },
    { label: "Sulaymaniyah", value: "Sulaymaniyah" },
  ],

  Ireland: [
    { label: "Dublin", value: "Dublin" },
    { label: "Cork", value: "Cork" },
    { label: "Limerick", value: "Limerick" },
    { label: "Galway", value: "Galway" },
    { label: "Waterford", value: "Waterford" },
    { label: "Drogheda", value: "Drogheda" },
    { label: "Swords", value: "Swords" },
    { label: "Bray", value: "Bray" },
  ],

  Israel: [
    { label: "Jerusalem", value: "Jerusalem" },
    { label: "Tel Aviv", value: "Tel Aviv" },
    { label: "Haifa", value: "Haifa" },
    { label: "Rishon LeZion", value: "Rishon LeZion" },
    { label: "Petah Tikva", value: "Petah Tikva" },
    { label: "Ashdod", value: "Ashdod" },
    { label: "Netanya", value: "Netanya" },
    { label: "Beersheba", value: "Beersheba" },
  ],

  Italy: [
    { label: "Rome", value: "Rome" },
    { label: "Milan", value: "Milan" },
    { label: "Naples", value: "Naples" },
    { label: "Turin", value: "Turin" },
    { label: "Florence", value: "Florence" },
    { label: "Bologna", value: "Bologna" },
    { label: "Venice", value: "Venice" },
    { label: "Verona", value: "Verona" },
    { label: "Genoa", value: "Genoa" },
    { label: "Palermo", value: "Palermo" },
  ],

  Japan: [
    { label: "Tokyo", value: "Tokyo" },
    { label: "Osaka", value: "Osaka" },
    { label: "Kyoto", value: "Kyoto" },
    { label: "Yokohama", value: "Yokohama" },
    { label: "Nagoya", value: "Nagoya" },
    { label: "Sapporo", value: "Sapporo" },
    { label: "Fukuoka", value: "Fukuoka" },
    { label: "Kobe", value: "Kobe" },
    { label: "Kawasaki", value: "Kawasaki" },
    { label: "Saitama", value: "Saitama" },
    { label: "Hiroshima", value: "Hiroshima" },
    { label: "Sendai", value: "Sendai" },
  ],

  Kazakhstan: [
    { label: "Nur-Sultan", value: "Nur-Sultan" },
    { label: "Almaty", value: "Almaty" },
    { label: "Shymkent", value: "Shymkent" },
    { label: "Karagandy", value: "Karagandy" },
    { label: "Aktobe", value: "Aktobe" },
    { label: "Taraz", value: "Taraz" },
    { label: "Pavlodar", value: "Pavlodar" },
    { label: "Semey", value: "Semey" },
  ],

  Latvia: [
    { label: "Riga", value: "Riga" },
    { label: "Daugavpils", value: "Daugavpils" },
    { label: "Liepāja", value: "Liepaja" },
    { label: "Jelgava", value: "Jelgava" },
    { label: "Jūrmala", value: "Jurmala" },
    { label: "Ventspils", value: "Ventspils" },
    { label: "Rēzekne", value: "Rezekne" },
    { label: "Valmiera", value: "Valmiera" },
  ],

  Lebanon: [
    { label: "Beirut", value: "Beirut" },
    { label: "Tripoli", value: "Tripoli" },
    { label: "Sidon", value: "Sidon" },
    { label: "Tyre", value: "Tyre" },
    { label: "Baalbek", value: "Baalbek" },
    { label: "Jounieh", value: "Jounieh" },
    { label: "Zahle", value: "Zahle" },
    { label: "Byblos", value: "Byblos" },
  ],

  Lithuania: [
    { label: "Vilnius", value: "Vilnius" },
    { label: "Kaunas", value: "Kaunas" },
    { label: "Klaipėda", value: "Klaipeda" },
    { label: "Šiauliai", value: "Siauliai" },
    { label: "Panevėžys", value: "Panevezys" },
    { label: "Alytus", value: "Alytus" },
    { label: "Marijampolė", value: "Marijampole" },
    { label: "Mažeikiai", value: "Mazeikiai" },
  ],

  Luxembourg: [
    { label: "Luxembourg City", value: "Luxembourg City" },
    { label: "Esch-sur-Alzette", value: "Esch-sur-Alzette" },
    { label: "Differdange", value: "Differdange" },
    { label: "Dudelange", value: "Dudelange" },
    { label: "Ettelbruck", value: "Ettelbruck" },
    { label: "Diekirch", value: "Diekirch" },
    { label: "Wiltz", value: "Wiltz" },
    { label: "Echternach", value: "Echternach" },
  ],

  Malaysia: [
    { label: "Kuala Lumpur", value: "Kuala Lumpur" },
    { label: "George Town", value: "George Town" },
    { label: "Johor Bahru", value: "Johor Bahru" },
    { label: "Ipoh", value: "Ipoh" },
    { label: "Shah Alam", value: "Shah Alam" },
    { label: "Petaling Jaya", value: "Petaling Jaya" },
    { label: "Malacca City", value: "Malacca City" },
    { label: "Kuching", value: "Kuching" },
    { label: "Kota Kinabalu", value: "Kota Kinabalu" },
    { label: "Alor Setar", value: "Alor Setar" },
  ],

  Mexico: [
    { label: "Mexico City", value: "Mexico City" },
    { label: "Guadalajara", value: "Guadalajara" },
    { label: "Monterrey", value: "Monterrey" },
    { label: "Puebla", value: "Puebla" },
    { label: "Tijuana", value: "Tijuana" },
    { label: "Cancún", value: "Cancun" },
    { label: "Mérida", value: "Merida" },
    { label: "León", value: "Leon" },
    { label: "Querétaro", value: "Queretaro" },
    { label: "Ciudad Juárez", value: "Ciudad Juarez" },
  ],

  Moldova: [
    { label: "Chișinău", value: "Chisinau" },
    { label: "Tiraspol", value: "Tiraspol" },
    { label: "Bălți", value: "Balti" },
    { label: "Bender", value: "Bender" },
    { label: "Rîbnița", value: "Ribnita" },
    { label: "Cahul", value: "Cahul" },
    { label: "Ungheni", value: "Ungheni" },
    { label: "Soroca", value: "Soroca" },
  ],

  Netherlands: [
    { label: "Amsterdam", value: "Amsterdam" },
    { label: "Rotterdam", value: "Rotterdam" },
    { label: "The Hague", value: "The Hague" },
    { label: "Utrecht", value: "Utrecht" },
    { label: "Eindhoven", value: "Eindhoven" },
    { label: "Groningen", value: "Groningen" },
    { label: "Tilburg", value: "Tilburg" },
    { label: "Almere", value: "Almere" },
    { label: "Breda", value: "Breda" },
    { label: "Nijmegen", value: "Nijmegen" },
  ],

  "New Zealand": [
    { label: "Auckland", value: "Auckland" },
    { label: "Wellington", value: "Wellington" },
    { label: "Christchurch", value: "Christchurch" },
    { label: "Hamilton", value: "Hamilton" },
    { label: "Tauranga", value: "Tauranga" },
    { label: "Napier", value: "Napier" },
    { label: "Dunedin", value: "Dunedin" },
    { label: "Palmerston North", value: "Palmerston North" },
    { label: "Nelson", value: "Nelson" },
    { label: "Rotorua", value: "Rotorua" },
  ],

  Norway: [
    { label: "Oslo", value: "Oslo" },
    { label: "Bergen", value: "Bergen" },
    { label: "Trondheim", value: "Trondheim" },
    { label: "Stavanger", value: "Stavanger" },
    { label: "Drammen", value: "Drammen" },
    { label: "Fredrikstad", value: "Fredrikstad" },
    { label: "Kristiansand", value: "Kristiansand" },
    { label: "Tromsø", value: "Tromso" },
  ],

  Philippines: [
    { label: "Manila", value: "Manila" },
    { label: "Quezon City", value: "Quezon City" },
    { label: "Davao City", value: "Davao City" },
    { label: "Cebu City", value: "Cebu City" },
    { label: "Zamboanga City", value: "Zamboanga City" },
    { label: "Baguio", value: "Baguio" },
    { label: "Iloilo City", value: "Iloilo City" },
    { label: "Bacolod", value: "Bacolod" },
    { label: "Cagayan de Oro", value: "Cagayan de Oro" },
    { label: "Angeles City", value: "Angeles City" },
  ],

  Poland: [
    { label: "Warsaw", value: "Warsaw" },
    { label: "Kraków", value: "Krakow" },
    { label: "Łódź", value: "Lodz" },
    { label: "Wrocław", value: "Wroclaw" },
    { label: "Poznań", value: "Poznan" },
    { label: "Gdańsk", value: "Gdansk" },
    { label: "Szczecin", value: "Szczecin" },
    { label: "Bydgoszcz", value: "Bydgoszcz" },
    { label: "Lublin", value: "Lublin" },
    { label: "Katowice", value: "Katowice" },
  ],

  Portugal: [
    { label: "Lisbon", value: "Lisbon" },
    { label: "Porto", value: "Porto" },
    { label: "Braga", value: "Braga" },
    { label: "Coimbra", value: "Coimbra" },
    { label: "Faro", value: "Faro" },
    { label: "Funchal", value: "Funchal" },
    { label: "Aveiro", value: "Aveiro" },
    { label: "Évora", value: "Evora" },
    { label: "Portimão", value: "Portimao" },
    { label: "Viseu", value: "Viseu" },
  ],

  Romania: [
    { label: "Bucharest", value: "Bucharest" },
    { label: "Cluj-Napoca", value: "Cluj-Napoca" },
    { label: "Timișoara", value: "Timisoara" },
    { label: "Iași", value: "Iasi" },
    { label: "Constanța", value: "Constanta" },
    { label: "Craiova", value: "Craiova" },
    { label: "Brașov", value: "Brasov" },
    { label: "Galați", value: "Galati" },
    { label: "Ploiești", value: "Ploiesti" },
    { label: "Oradea", value: "Oradea" },
  ],

  Russia: [
    { label: "Moscow", value: "Moscow" },
    { label: "Saint Petersburg", value: "Saint Petersburg" },
    { label: "Novosibirsk", value: "Novosibirsk" },
    { label: "Yekaterinburg", value: "Yekaterinburg" },
    { label: "Kazan", value: "Kazan" },
    { label: "Nizhny Novgorod", value: "Nizhny Novgorod" },
    { label: "Chelyabinsk", value: "Chelyabinsk" },
    { label: "Samara", value: "Samara" },
    { label: "Omsk", value: "Omsk" },
    { label: "Rostov-on-Don", value: "Rostov-on-Don" },
  ],

  "Saudi Arabia": [
    { label: "Riyadh", value: "Riyadh" },
    { label: "Jeddah", value: "Jeddah" },
    { label: "Mecca", value: "Mecca" },
    { label: "Medina", value: "Medina" },
    { label: "Dammam", value: "Dammam" },
    { label: "Khobar", value: "Khobar" },
    { label: "Taif", value: "Taif" },
    { label: "Tabuk", value: "Tabuk" },
    { label: "Buraidah", value: "Buraidah" },
    { label: "Khamis Mushait", value: "Khamis Mushait" },
  ],

  Serbia: [
    { label: "Belgrade", value: "Belgrade" },
    { label: "Novi Sad", value: "Novi Sad" },
    { label: "Niš", value: "Nis" },
    { label: "Kragujevac", value: "Kragujevac" },
    { label: "Subotica", value: "Subotica" },
    { label: "Zrenjanin", value: "Zrenjanin" },
    { label: "Pančevo", value: "Pancevo" },
    { label: "Čačak", value: "Cacak" },
  ],

  Singapore: [
    { label: "Singapore", value: "Singapore" },
  ],

  Slovakia: [
    { label: "Bratislava", value: "Bratislava" },
    { label: "Košice", value: "Kosice" },
    { label: "Prešov", value: "Presov" },
    { label: "Žilina", value: "Zilina" },
    { label: "Banská Bystrica", value: "Banska Bystrica" },
    { label: "Nitra", value: "Nitra" },
    { label: "Trnava", value: "Trnava" },
    { label: "Martin", value: "Martin" },
  ],

  Slovenia: [
    { label: "Ljubljana", value: "Ljubljana" },
    { label: "Maribor", value: "Maribor" },
    { label: "Celje", value: "Celje" },
    { label: "Kranj", value: "Kranj" },
    { label: "Velenje", value: "Velenje" },
    { label: "Koper", value: "Koper" },
    { label: "Novo Mesto", value: "Novo Mesto" },
    { label: "Ptuj", value: "Ptuj" },
  ],

  "South Africa": [
    { label: "Johannesburg", value: "Johannesburg" },
    { label: "Cape Town", value: "Cape Town" },
    { label: "Durban", value: "Durban" },
    { label: "Pretoria", value: "Pretoria" },
    { label: "Port Elizabeth", value: "Port Elizabeth" },
    { label: "Bloemfontein", value: "Bloemfontein" },
    { label: "East London", value: "East London" },
    { label: "Pietermaritzburg", value: "Pietermaritzburg" },
    { label: "Kimberley", value: "Kimberley" },
    { label: "Nelspruit", value: "Nelspruit" },
  ],

  "South Korea": [
    { label: "Seoul", value: "Seoul" },
    { label: "Busan", value: "Busan" },
    { label: "Incheon", value: "Incheon" },
    { label: "Daegu", value: "Daegu" },
    { label: "Daejeon", value: "Daejeon" },
    { label: "Gwangju", value: "Gwangju" },
    { label: "Suwon", value: "Suwon" },
    { label: "Ulsan", value: "Ulsan" },
    { label: "Changwon", value: "Changwon" },
    { label: "Seongnam", value: "Seongnam" },
  ],

  Spain: [
    { label: "Madrid", value: "Madrid" },
    { label: "Barcelona", value: "Barcelona" },
    { label: "Valencia", value: "Valencia" },
    { label: "Seville", value: "Seville" },
    { label: "Bilbao", value: "Bilbao" },
    { label: "Malaga", value: "Malaga" },
    { label: "Zaragoza", value: "Zaragoza" },
    { label: "Murcia", value: "Murcia" },
    { label: "Palma", value: "Palma" },
    { label: "Granada", value: "Granada" },
  ],

  Sweden: [
    { label: "Stockholm", value: "Stockholm" },
    { label: "Gothenburg", value: "Gothenburg" },
    { label: "Malmö", value: "Malmo" },
    { label: "Uppsala", value: "Uppsala" },
    { label: "Västerås", value: "Vasteras" },
    { label: "Örebro", value: "Orebro" },
    { label: "Linköping", value: "Linkoping" },
    { label: "Helsingborg", value: "Helsingborg" },
    { label: "Jönköping", value: "Jonkoping" },
    { label: "Norrköping", value: "Norrkoping" },
  ],

  Switzerland: [
    { label: "Zurich", value: "Zurich" },
    { label: "Geneva", value: "Geneva" },
    { label: "Basel", value: "Basel" },
    { label: "Lausanne", value: "Lausanne" },
    { label: "Bern", value: "Bern" },
    { label: "Lucerne", value: "Lucerne" },
    { label: "St. Gallen", value: "St. Gallen" },
    { label: "Lugano", value: "Lugano" },
    { label: "Fribourg", value: "Fribourg" },
    { label: "Neuchâtel", value: "Neuchatel" },
  ],

  Thailand: [
    { label: "Bangkok", value: "Bangkok" },
    { label: "Phuket", value: "Phuket" },
    { label: "Chiang Mai", value: "Chiang Mai" },
    { label: "Pattaya", value: "Pattaya" },
    { label: "Hat Yai", value: "Hat Yai" },
    { label: "Khon Kaen", value: "Khon Kaen" },
    { label: "Nakhon Ratchasima", value: "Nakhon Ratchasima" },
    { label: "Udon Thani", value: "Udon Thani" },
    { label: "Surat Thani", value: "Surat Thani" },
    { label: "Chiang Rai", value: "Chiang Rai" },
  ],

  Turkey: [
    { label: "Istanbul", value: "Istanbul" },
    { label: "Ankara", value: "Ankara" },
    { label: "Izmir", value: "Izmir" },
    { label: "Bursa", value: "Bursa" },
    { label: "Antalya", value: "Antalya" },
    { label: "Adana", value: "Adana" },
    { label: "Konya", value: "Konya" },
    { label: "Gaziantep", value: "Gaziantep" },
    { label: "Mersin", value: "Mersin" },
    { label: "Diyarbakır", value: "Diyarbakir" },
  ],

  Ukraine: [
    { label: "Kyiv", value: "Kyiv" },
    { label: "Kharkiv", value: "Kharkiv" },
    { label: "Odesa", value: "Odesa" },
    { label: "Dnipro", value: "Dnipro" },
    { label: "Donetsk", value: "Donetsk" },
    { label: "Lviv", value: "Lviv" },
    { label: "Zaporizhzhia", value: "Zaporizhzhia" },
    { label: "Kryvyi Rih", value: "Kryvyi Rih" },
    { label: "Mykolaiv", value: "Mykolaiv" },
    { label: "Mariupol", value: "Mariupol" },
  ],

  "United Arab Emirates": [
    { label: "Dubai", value: "Dubai" },
    { label: "Abu Dhabi", value: "Abu Dhabi" },
    { label: "Sharjah", value: "Sharjah" },
    { label: "Al Ain", value: "Al Ain" },
    { label: "Ajman", value: "Ajman" },
    { label: "Ras Al Khaimah", value: "Ras Al Khaimah" },
    { label: "Fujairah", value: "Fujairah" },
    { label: "Umm Al Quwain", value: "Umm Al Quwain" },
  ],

  "United Kingdom": [
    { label: "London", value: "London" },
    { label: "Manchester", value: "Manchester" },
    { label: "Birmingham", value: "Birmingham" },
    { label: "Liverpool", value: "Liverpool" },
    { label: "Leeds", value: "Leeds" },
    { label: "Glasgow", value: "Glasgow" },
    { label: "Edinburgh", value: "Edinburgh" },
    { label: "Bristol", value: "Bristol" },
    { label: "Sheffield", value: "Sheffield" },
    { label: "Newcastle", value: "Newcastle" },
    { label: "Cardiff", value: "Cardiff" },
    { label: "Belfast", value: "Belfast" },
  ],

  "United States": [
    { label: "New York", value: "New York" },
    { label: "Los Angeles", value: "Los Angeles" },
    { label: "Chicago", value: "Chicago" },
    { label: "Houston", value: "Houston" },
    { label: "Miami", value: "Miami" },
    { label: "San Francisco", value: "San Francisco" },
    { label: "Boston", value: "Boston" },
    { label: "Seattle", value: "Seattle" },
    { label: "Denver", value: "Denver" },
    { label: "Atlanta", value: "Atlanta" },
    { label: "Philadelphia", value: "Philadelphia" },
    { label: "Phoenix", value: "Phoenix" },
    { label: "Dallas", value: "Dallas" },
    { label: "San Diego", value: "San Diego" },
    { label: "Las Vegas", value: "Las Vegas" },
  ],

  Uzbekistan: [
    { label: "Tashkent", value: "Tashkent" },
    { label: "Samarkand", value: "Samarkand" },
    { label: "Bukhara", value: "Bukhara" },
    { label: "Namangan", value: "Namangan" },
    { label: "Andijan", value: "Andijan" },
    { label: "Nukus", value: "Nukus" },
    { label: "Fergana", value: "Fergana" },
    { label: "Qarshi", value: "Qarshi" },
  ],

  Vietnam: [
    { label: "Hanoi", value: "Hanoi" },
    { label: "Ho Chi Minh City", value: "Ho Chi Minh City" },
    { label: "Da Nang", value: "Da Nang" },
    { label: "Hai Phong", value: "Hai Phong" },
    { label: "Can Tho", value: "Can Tho" },
    { label: "Nha Trang", value: "Nha Trang" },
    { label: "Hue", value: "Hue" },
    { label: "Da Lat", value: "Da Lat" },
  ],
};